name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore EarlyXrm.QueryExpressionExtensions.sln

    - name: Build
      run: msbuild EarlyXrm.QueryExpressionExtensions.sln /p:Configuration=Release

    - name: Test
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      
    - name: Pack QueryExpressionExtensions
      run: msbuild -t:pack EarlyXrm.QueryExpressionExtensions\EarlyXrm.QueryExpressionExtensions.csproj /p:Configuration=Release
      
    - name: Pack QueryExpressionExtensions.Linked
      run: msbuild -t:pack EarlyXrm.QueryExpressionExtensions.Linked\EarlyXrm.QueryExpressionExtensions.Linked.csproj /p:Configuration=Release
      
    - name: Publish build artifacts
      uses: actions/upload-artifact@master
      with:
        name: packages
        path: bin/Release/**/*.nupkg

    - name: Add Github Source
      run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -Username ${{ github.repository_owner }} -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Push to github
      run: nuget push **/*.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      
