name: CI

on:
  push:
    branches:
     - '**'
    tags:
     - 'v*.*.*'
  pull_request:
    branches:
     - '**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
          useConfigFile: true
          configFilePath: ./GitVersion.yml

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7
        
    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore EarlyXrm.QueryExpressionExtensions.sln

    - uses: microsoft/variable-substitution@v1 
      with:
        files: EarlyXrm.QueryExpressionExtensions.IntegrationTests\appsettings.json
      env:
        ConnectionStrings.Crm: ${{secrets.CrmConnectionString}}

    - name: Build
      run: msbuild EarlyXrm.QueryExpressionExtensions.sln /p:Configuration=Release

    - name: Unit Tests
      #run: dotnet test -c Release --no-build --filter FullyQualifiedName~UnitTests /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:Exclude="[*.*Tests]*" --filter FullyQualifiedName~UnitTests /p:MergeWith="$GITHUB_WORKSPACE/coverage/coverage.json" /p:CoverletOutputFormat="lcov%2cjson" -m:1

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: D:\a\EarlyXrm.QueryExpressionExtensions\EarlyXrm.QueryExpressionExtensions\EarlyXrm.QueryExpressionExtensions.UnitTests\coverage.info

    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.7
      with:
        reports: "**/coverage*cobertura.xml"
        targetdir: "Report"
        reporttypes: "HtmlInline;Cobertura"
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: Publish coverage report
      uses: 5monkeys/cobertura-action@master
      with:
        path: Report/Cobertura.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 75

    - run: Install-Module -Force -Name Xrm.Framework.CI.PowerShell.Cmdlets
      shell: powershell
      
    - run: Select-WhoAmI -ConnectionString:"${{secrets.CrmConnectionString}}"
      shell: powershell

    - run: Get-Content EarlyXrm.QueryExpressionExtensions.IntegrationTests\bin\Release\net462\appsettings.json
      shell: powershell

    - name: Integration Tests
      run: dotnet test -c Release --no-build --filter FullyQualifiedName~IntegrationTests
      
    - name: Pack QueryExpressionExtensions
      run: msbuild -t:pack EarlyXrm.QueryExpressionExtensions\EarlyXrm.QueryExpressionExtensions.csproj /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
      
    - name: Pack QueryExpressionExtensions.Linked
      run: msbuild -t:pack EarlyXrm.QueryExpressionExtensions.Linked\EarlyXrm.QueryExpressionExtensions.Linked.csproj /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
      
    - name: Publish build artifacts
      uses: actions/upload-artifact@master
      with:
        name: packages
        path: ./**/EarlyXrm.QueryExpressionExtensions*.nupkg

    - name: Add Github Source
      run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -Username ${{ github.repository_owner }} -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Delete old packages
      uses: smartsquaregmbh/delete-old-packages@v0.3.1
      with:
        keep: 2
        names: |
          EarlyXrm.QueryExpressionExtensions
          EarlyXrm.QueryExpressionExtensions.Linked

    - name: Push to github
      run: nuget push **/EarlyXrm.QueryExpressionExtensions*.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -SkipDuplicate

    - name: Push to nuget.org
      run: nuget push **/EarlyXrm.QueryExpressionExtensions*.nupkg -ApiKey ${{ secrets.NUGET_APIKEY }} -source https://api.nuget.org/v3/index.json